name: Build

on:
  push:
    branches:
      - releases/**
  workflow_dispatch:

jobs:
  lint:
    name: Build packages into wheel and sdist
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry

      - name: Install python package
        run: |
          poetry config virtualenvs.create false
          poetry install

      - name: Build all packages
        run: |
          repo build

      - name: List packages
        run: |
          ls -lhtr dist/

      - name: Write changelog update
        run: |
          git diff HEAD^ HEAD --unified=0 CHANGELOG.md | tail +6 | sed -e 's/^\+//' | sed 1d > CHANGES.md

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          # TODO: Specify prerelease when that's the case
          # prerelease: 
          body_path: CHANGES.md
          files: |
            dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_REPOSITORY: charbonnierg/repo
