name: Release

on: 
  workflow_dispatch:

jobs:
  lint:
    name: Execute semantic release on packages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry

      - name: Install python package
        run: |
          poetry config virtualenvs.create false
          poetry install

      - name: Install NodeJS and npm
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install semantic release and its dependencies
        run: |
          npm i -g semantic-release \
            @semantic-release/changelog \
            @semantic-release/exec \
            conventional-changelog-conventionalcommits

      - name: Run semantic release
        run: |
          semantic-release --debug
